### ISSUE TITLE
Generalizing Data.Conduit.Async

### ISSUE THREAD

**Issue by rjmac** [cgaebel/stm-conduit#31]
I've made [an attempt](https://github.com/rjmac/stm-conduit-generalized/blob/master/CConduit.hs) at generalizing `Data.Conduit.Async` to allow for more than one concurrency join point, in order to allow code that looks like
```haskell
   fromNetwork $$& (process &= process &= process) $=& toNetwork
```
or
```haskell
   fromNetwork $$& (process &= process &= process) `buf` toNetwork
      where buf = bufferToFile' 1000 Nothing "/tmp"
```

I may have gone a little overboard in the type magic to overload `$$&` and `$=&` this way, but at least code using it looks nice and it should be source-compatible with almost all existing stm-conduit user code.  If you're interested, I can clean this up into a proper pull request, as right now it's a completely separate project that I didn't realize would become this exactly when I started.

**Comment by cgaebel** [comment]
If you're actively using it in some other code, and the pull request includes both a test and example in the documentation, I wouldn't be against it!
