### ISSUE TITLE
mergeSources and brackets

### ISSUE THREAD

**Issue by AlexeyRaga** [cgaebel/stm-conduit#36]
I am having an issue with using `bracketP`/`ResourceT` with `mergeSources`:

- The allocated resource is a connection to an external system (a queue)
- I am using `mergeSources` to join two or more conduit sources which are reading from different queues but are sharing the same connection
- When the resource is released the connection gets terminated, but the underlying sources don't know about it and keep trying to consume more messages from their queues
- I get an exception for accessing closed connection.

The easiest way to reproduce it is to add `=$= take 1` to the result stream after `mergeSources`. After the 1st element is consumed by the sink the pipe is exhausted and the resource finaliser is called. The exception of accessing the closed resource follows.

Is it a bug or what would be the proper way to terminate "merged" sources?

**Comment by cgaebel** [comment]
@bfops looks like the original `merge*` came from a PR from you. Do you know the answer to this question?

**Comment by bfops** [comment]
It's been a couple of years since this PR. I can't remember off the top of my head how termination usually works for sources, but maybe step one is to turn the exception into a `Maybe`, and then use that to signal termination to the source?

**Comment by AlexeyRaga** [comment]
I could probably do that but with this solution there will be no way to distinguish between "genuine" exceptions and a proper termination, which should be handled differently (retry if the connection broke etc).

**Comment by AlexeyRaga** [comment]
Maybe another channel or *Var can be used to indicate that the downstream is closed so the upstream sinks (ones that read from underlying sources and push to the channel) would close too?
Or doing it through the `ResourceT` would be possible?

**Comment by qnikst** [comment]
Not sure if I'm right person to decide here but I think that current semantics is the following:

`mergeSources` - consume the data from sources until any of them is available, this means that `mergeSources` can't notify upstream about problems with other upstreams, or do anything sane in generic way, it just doesn't have enough information.

I think if you have dependencies between sources, then you need somehow express that on the sources level by either introducing a some flag, that will show if underlying resource is available, or throw exception.

**Comment by qnikst** [comment]
Sorry seems I misunderstood your problem, I think it should be addressed by #42.
