### ISSUE TITLE
Expose `CCatable` class

### ISSUE THREAD

**Issue by parsonsmatt** [cgaebel/stm-conduit#48]
Currently, if I write my own operator alias for `buffer` with a different buffer size, I cannot give it a polymorphic type signature, as the `CCatable` class isn't exported.

```haskell
(.|&) = STMConduit.buffer ...
```

is going to monomorphize to either `Conduit` or `CConduit`, which means I can't use it for eg `Data.Conduit.List.mapM`.

**Comment by cgaebel** [comment]
I'd accept that patch.

**Comment by qnikst** [comment]
Hello, @parsonsmatt sorry for the late response, can you please check #59, does it solve your request?
