### ISSUE TITLE
What is the difference between `mergeSources` and `mergeConduits` ?

### ISSUE THREAD

**Issue by SamProtas** [cgaebel/stm-conduit#49]
At first glance I assumed `mergeSources` would concurrently produce values from the provided  `Source`s and provide a single `Source` from which these can be read.

In essence this create a single `Source` which internally was concurrently generating the values to pass downstream.

I then assumed that `mergeConduits` would return a `Conduit` which would:

1) Accept inputs from upstream

2) Distribute the inputs across the provided `Conduit`s for concurrent processing

3) Join the output of the provided `Conduit`s into a single output stream.

In essence I assumed this would be creating a single `Conduit` that internally processed values concurrently.

After reading the code and playing around with this a bit it seems that the returned `Conduit` never `await`s values from upstream, it only pulls values from the internally managed `TBMChan`. Considering this, it's not really returning a `Conduit`, it's actually a `Source`.

I don't think this was the intended behavior of this function based on it's test. For instance, if you edit `test_mergeConduits` to input (and expect) `[1..20]` instead of `[1..10]` you'll see it fails with 

`ERROR: thread blocked indefinitely in an STM transaction`

The only reason the test currently passes is because the internal `TBMChan` is large enough to hold the entirety of the upstream values.

Is this a bug?

Should the the returned `Conduit` from `mergeConduits` behave as I expected?

**Comment by qnikst** [comment]
Sorry for the late response.  You should ignore `mergeConduit` it could not have any sane semantics, and will be deprecated in the next version, and removed in the next+1 version. Currently `mergeConduit` takes all possible input from upstream, feeds that to all conduits and then start streaming replies downstream. This function is in fact non-streaming, and I don't see how is it possible to fix it.

Merge Sources still provide an access to the stream of concurrently consumed sources, that are closed when downstream is finished, that stream is terminated when all sources have finished.

**Comment by SamProtas** [comment]
Thanks for the reply and clarification. I spent a bit of time trying to re-write mergeConduit myself and came to the same conclusion. 👍

**Comment by bbarker** [comment]
Would it be possible to have variants of mergeConduit that handle specific cases? new to conduit so maybe i'm not aware of its limitations. Looking at Scala examples that are somewhat easy to understand [here](https://github.com/OlivierBlanvillain/monadic-html): some possible variants are `zip`, `merge`, and `sampleOn`.

**Comment by qnikst** [comment]
as I said the `mergeCounduit` itself doesn't look like the right tool to achieve the task. I'm not sure that conduits itself is the right tool to do the job. As they are more related to a single executor pipeline, such combinators are pretty easy to write in pure `stm` and you can lift that STM action into a conduit pipeline.

If you are working with `STM a` actions then we can just write.
```
zip = liftA2 zip
merge = (<|>)
sampeOn f g = flip fix Await $ \next st -> asum [Left <$> f, Right <$> g] >>= \x ->
   case (ex, st) of
    (Left x, Push) -> pure x
    (Left x, _) -> next (Value x)
    (Right g, Value x) -> next
    (Right g,_) -> next Push
```
I see a value in such combinator, so it may worth adding them to this library or something more general purpose one?
