### ISSUE TITLE
remove conduit-combinators in stm-conduit.cabal in branch conduit-1.3

### ISSUE THREAD

**Issue by ruomad** [cgaebel/stm-conduit#50]
the functionality has been merged in conduit and the two packages are incompatible now

**Comment by qnikst** [comment]
Thanks for the report the change will be applied as a part of the #51. Release on the hackage (and stackage) will be done later this week;  I have to verify that all documentation is still up to date.

**Comment by qnikst** [comment]
I'm closing this task, as fix has hit the master. It will be released as 4.0.0 on hackage.
