### ISSUE TITLE
stm-conduit-3.0.0 does not build against current conduit-combinators package

### ISSUE THREAD

**Issue by gzh** [cgaebel/stm-conduit#52]
As far as I can see the stm-conduit-3.0.0 was designed with conduit < 1.3. conduit-combinators was a separate package prior to conduit-1.3. At some point, it was marked as deprecated and all of its content was purged (in fact merged to conduit-1.3). That "purged" version is uploaded to hackage and marked as conduit-combinators-1.3.0.

Now, if we take stm-conduit-3.0.0 and try to build it, cabal-install will take conduit<1.3 but conduit-combinators-1.3 which would result in effective absence of the body of the conduit-combinators. Given that, stm-conduit does not compile with what is in hackage today:
<details><summary>build output</summary>
<pre>
gzh@vmdeb9:~/tmp$ cabal sandbox init
Writing a default package environment file to
/home/gzh/tmp/cabal.sandbox.config
Creating a new sandbox at /home/gzh/tmp/.cabal-sandbox
gzh@vmdeb9:~/tmp$ cabal install stm-conduit-3.0.0
Resolving dependencies...
Notice: installing into a sandbox located at /home/gzh/tmp/.cabal-sandbox
Configuring cereal-0.5.5.0...
Configuring conduit-combinators-1.3.0...
Configuring integer-logarithms-1.0.2.1...
Configuring mtl-2.2.2...
Configuring primitive-0.6.4.0...
Configuring random-1.1...
Configuring semigroups-0.18.5...
Configuring unliftio-core-0.1.1.0...
Configuring void-0.7.2...
Configuring monad-loops-0.4.3...
Configuring base-orphans-0.8...
Configuring stm-2.4.5.0...
Configuring zlib-0.6.2...
Configuring transformers-compat-0.6.2...
Configuring text-1.2.3.0...
Configuring network-2.7.0.1...
Building cereal-0.5.5.0...
Building mtl-2.2.2...
Building conduit-combinators-1.3.0...
Building integer-logarithms-1.0.2.1...
Building random-1.1...
Building semigroups-0.18.5...
Building unliftio-core-0.1.1.0...
Building monad-loops-0.4.3...
Building base-orphans-0.8...
Building stm-2.4.5.0...
Building void-0.7.2...
Building primitive-0.6.4.0...
Building zlib-0.6.2...
Building text-1.2.3.0...
Building transformers-compat-0.6.2...
Installed void-0.7.2
Installed conduit-combinators-1.3.0
Installed semigroups-0.18.5
Installed unliftio-core-0.1.1.0
Installed monad-loops-0.4.3
Installed integer-logarithms-1.0.2.1
Installed stm-2.4.5.0
Configuring stm-chans-3.0.0.4...
Installed base-orphans-0.8
Building network-2.7.0.1...
Installed mtl-2.2.2
Installed transformers-compat-0.6.2
Configuring transformers-base-0.4.5.2...
Configuring mmorph-1.1.2...
Configuring exceptions-0.10.0...
Building stm-chans-3.0.0.4...
Building exceptions-0.10.0...
Building transformers-base-0.4.5.2...
Building mmorph-1.1.2...
Installed transformers-base-0.4.5.2
Configuring monad-control-1.0.2.3...
Installed mmorph-1.1.2
Building monad-control-1.0.2.3...
Installed stm-chans-3.0.0.4
Installed random-1.1
Installed monad-control-1.0.2.3
Configuring lifted-base-0.2.3.12...
Installed exceptions-0.10.0
Installed zlib-0.6.2
Building lifted-base-0.2.3.12...
Installed lifted-base-0.2.3.12
Configuring resourcet-1.1.11...
Building resourcet-1.1.11...
Installed network-2.7.0.1
Installed resourcet-1.1.11
Installed primitive-0.6.4.0
Configuring conduit-1.2.13.1...
Building conduit-1.2.13.1...
Installed cereal-0.5.5.0
Installed conduit-1.2.13.1
Configuring cereal-conduit-0.7.3...
Building cereal-conduit-0.7.3...
Installed cereal-conduit-0.7.3
Installed text-1.2.3.0
Configuring hashable-1.2.7.0...
Configuring blaze-builder-0.4.1.0...
Building hashable-1.2.7.0...
Building blaze-builder-0.4.1.0...
Installed hashable-1.2.7.0
Configuring constraints-0.10.1...
Configuring async-2.2.1...
Configuring scientific-0.3.6.2...
Building constraints-0.10.1...
Building scientific-0.3.6.2...
Building async-2.2.1...
Installed blaze-builder-0.4.1.0
Installed async-2.2.1
Configuring typed-process-0.2.2.0...
Configuring streaming-commons-0.1.19...
Building typed-process-0.2.2.0...
Building streaming-commons-0.1.19...
Installed constraints-0.10.1
Configuring lifted-async-0.10.0.2...
Installed typed-process-0.2.2.0
Building lifted-async-0.10.0.2...
Installed scientific-0.3.6.2
Configuring attoparsec-0.13.2.2...
Building attoparsec-0.13.2.2...
Installed lifted-async-0.10.0.2
Installed streaming-commons-0.1.19
Installed attoparsec-0.13.2.2
Configuring conduit-extra-1.2.3.2...
Building conduit-extra-1.2.3.2...
Installed conduit-extra-1.2.3.2
Configuring stm-conduit-3.0.0...
Building stm-conduit-3.0.0...
Failed to install stm-conduit-3.0.0
Build log ( /home/gzh/tmp/.cabal-sandbox/logs/ghc-8.2.1/stm-conduit-3.0.0-JeGUQQcB8GpJmnDKT0Dhgk.log ):
cabal: Entering directory '/tmp/cabal-tmp-105076/stm-conduit-3.0.0'
Configuring stm-conduit-3.0.0...
Preprocessing library for stm-conduit-3.0.0..
Building library for stm-conduit-3.0.0..
[1 of 5] Compiling Data.Conduit.Async.Composition ( Data/Conduit/Async/Composition.hs, dist/dist-sandbox-9c730035/build/Data/Conduit/Async/Composition.o )

Data/Conduit/Async/Composition.hs:30:1: error:
    Could not find module `Conduit'
    Use -v to see a list of the files searched for.
   |
30 | import Conduit
   | ^^^^^^^^^^^^^^
cabal: Leaving directory '/tmp/cabal-tmp-105076/stm-conduit-3.0.0'
cabal: Error: some packages failed to install:
stm-conduit-3.0.0-JeGUQQcB8GpJmnDKT0Dhgk failed during the building phase. The
exception was:
ExitFailure 1
</pre>
</details>

I've got an obvious fix here https://github.com/gzh/stm-conduit/commit/9b47430cac65b2e47cdb19f9c00fd550bc9d5bd6
but cannot do a pull request because there's no 3.0.0 branch in your repository. That commit should be applied to commit aaba396c6b59ccecaa852ffb978ec8639acadff9, which looks like the latest 3.0.0 actually compatible with conduit < 1.3.

Do you think it's possible to upload a 3.0.0 revision 2 to hackage?

**Comment by qnikst** [comment]
I'm terribly sorry it took me too long to realize that the change needed is quite small.
I've updated a package revision.

**Comment by gzh** [comment]
Thank you!
