### ISSUE TITLE
errant line of code in gatherFrom?

### ISSUE THREAD

**Issue by bbarker** [cgaebel/stm-conduit#55]
I've yet to successfully use `gatherFrom`, possibly for various reasons, but one may be that `yield` takes place in a line that seems to never be used (i.e. the value is discarded):

https://github.com/cgaebel/stm-conduit/blob/f8710fcc8d4bcbe479a46d9bbb21d26b58feca74/Data/Conduit/Async.hs#L44

**Comment by qnikst** [comment]
Not sure that I'm getting the problem, `yield :: Monad m => o -> ConduitT i o m ()` - sends a value downstream and returns a tuple, we can always discard a tuple, and that is exactly what is done in this line, that is exactly the line that does all the job.

But maybe I'm missing something, can you clarify a bit more, if you think there is any problem.

**Comment by bbarker** [comment]
Sorry for the delayed reply - and I may be misunderstanding (something fundamental about Haskell even), but the last two monadic actions in `gather` are:

```haskell
        traverse_ yield xs
        case mres of
            Just (Left e)  -> liftIO $ throwIO (e :: SomeException)
            Just (Right r) -> return r
            Nothing        -> gather worker chan
```

Since `Monad m => m o -> ConduitT i o m ()`, it seems like the output `ConduitT` value needs to be emitted from the function, but since it is just used by `traverse_`, and that the line that `traverse_` is on isn't the last line of `gather`, it just seems like the result of performing the yields would be discarded. By the way, I'm not sure I understand what you meant when you said `yield` returns a tuple - it appears to return a `ConduitT`?

That said, I did see [some similar examples](https://github.com/snoyberg/conduit/blob/master/README.md#primitives):

```
    loop = do
        mx <- await
        case mx of
            Nothing -> return ()
            Just x -> do
                yield (f x)
                loop
```

In the recursive case, `yield (f x)` does not seem to be used in the recursive `loop` - it appears the value is discarded.

By the way, my main and obvious issue with `gatherFrom` is that I need a variant that waits forever for new input values, so as to be used with a server. I think I can manage to do that after understanding this bit of code.

**Comment by bbarker** [comment]
Woops, i finally got it. This `do` block is a Conduit do-block, so it maintains the internal state of what is happening down stream. Sorry!

**Comment by qnikst** [comment]
Let's not look at all the code in the hole and divide that into a smaller pieces and try to understand each one individually.
Explanation here will be a bit informal, but I hope that will not break your understanding.

So what conduit (or other streaming libraries) is? It's a set of the parts of pipeline that you can compose together using operator (`.|`). Call it `upstream .| downstream`. Each part of the pipe is isolated, apart from the internal logic it can:
   1. `await :: :: Monad m => Consumer i m (Maybe i)` — Get a value from upstream if there is any (`Just x`) or `Nothing` if upstream is entirely drained.
  2. `yield :: Monad m => o -> ConduitT i o m ()` — send a value downstream, returning unit value `()`.

So if you want to send anything further you call `yield`. You can craft some simple examples like:

```Haskell
> :m Conduit Data.Conduit.List
-- emit a value downstream
> runConduit $ do { yield 1 } .| consume
[1]
-- emit 2 values downstream
> runConduit $ do { yield 1 ; yield 2 } .| consume
[1,2]
```

Ok, with that? Now let's talk more about return value. From the type we see that it's `()` lets verify that:
```Haskell
>runConduit $ do { x <- yield 1 ; liftIO $ print x} .| consume
() -- <- here is return value
[1]
```

So there is no point in using the value (this by GHC doesn't complain about unused variables) in the second example.
In the first example we have a list of values, if we use `traverse` so result will not be discarded we will get `[()]` so we actually allocate a list of the values that are not needed, consuming memory and CPU for no reason. This why `traverse` is called.

Now back to your example:

```Haskell
loop = do
  mx <- await -- read next value from upstream
  case mx of   -- analyse the value
    Nothing -> return () -- the upstream was drained we just return a value
    Just x -> do
      yield (f x) -- we emit value downstream, this is where all the work is done
      loop -- we continue the process
```

Hope that helps.

**Comment by bbarker** [comment]
@qnikst it does, thank you! I'll save this post for later reference. I see what you mean about `traverse_` being preferable to `traverse`, for memory.
