### ISSUE TITLE
Alternative to gatherFrom: gatherForever

### ISSUE THREAD

**Issue by bbarker** [cgaebel/stm-conduit#56]
This is useful in a server context (for instance).  The only difference from `gatherFrom` is in the alternatives for `case mres` so that it now continues to check for values on the `TBQueue` (even if it is empty at some point). Given that, rather than having two functions, maybe having a parameter to `gatherFrom` to determine which `case mres` to use (wait forever or not) would be ok, but I don't have a strong preference on how to organize it.

```haskell
gatherForever :: forall m o. (MonadIO m, MonadUnliftIO m)
           => Int                -- ^ Size of the queue to create
           -> (TBQueue o -> m ()) -- ^ Action that generates output values
           -> ConduitT () o m ()
gatherForever size scatter = do
    chan   <- liftIO $ newTBQueueIO (fromIntegral size)
    worker <- lift $ async (scatter chan)
    res <- gather worker chan
    pure res
  where
    gather :: Async b -> TBQueue o -> ConduitT i o m b
    gather worker chan = do
        (xs :: [o], mres) <- liftIO $ atomically $ do
            xs <- whileM (not <$> isEmptyTBQueue chan) (readTBQueue chan)
            (xs,) <$> pollSTM worker
        traverse_ yield xs
        case mres of
            Just (Left e)  -> liftIO $ throwIO (e :: SomeException)
            _              -> gather worker chan
```

**Comment by qnikst** [comment]
Sorry for a late reply. As far as I see this function continues to check for values even the `worker` has exited. `gatherFrom` continues to check for values as well, but only while there are no more values in the chan and worker thread is alive.

It seems that such function can exit only with `BlockedIndefinitelyOnSTM` if there are no more threads that has a access to the `chan`. It feels pretty unsafe and I think that there should be better API for this case, but I may be wrong here. Can you please share the general structure of the code that uses this function, so we can check if it's the best option for the library in such a case?

**Comment by bbarker** [comment]
Hi @qnikst ,

I haven't had a chance to process all of what you said just yet (will try to read into this more soon), but I'm using this in a server context; when I used the original `gatherFrom`, it would exit immediately, perhaps because no TCP `accept` had been initiated when `gatherFrom` initially starts.

Here's how I used it, along with some surrounding context and discussion: https://github.com/google/proto-lens/issues/372#issuecomment-663648831

**Comment by qnikst** [comment]
Thanks, I'll take a deeper look, but from what I see the problem is that you immediately fork the thread from the worker, and worker exits:

```
serveTBQ hp port rFun tbq = do
    _ <- async $ withRunInIO $ \run -> TCP.serve hp port $ \(csock, addr) -> do
```

If you don't use `async` here then the code will work with `gatherFrom`.

**Comment by bbarker** [comment]
@qnikst sorry for taking a while to get back on this. I appreciate the feedback, and yes, that was indeed the issue. Hard to say why I had that `async` there in the first place, in retrospect.
